# Generated by Django 2.2.7 on 2020-06-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
