# Generated by Django 2.2.7 on 2020-06-28 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'O Positive'), ('A-', 'O Positive'), ('B+', 'O Positive'), ('B-', 'O Positive'), ('AB+', 'O Positive'), ('AB-', 'O Positive'), ('O+', 'O Positive'), ('O-', 'O Positive')], max_length=5)),
                ('permanent_address', models.CharField(max_length=100)),
                ('present_address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=20)),
                ('specific_area', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('last_date_of_donation', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
