# Generated by Django 2.2.7 on 2020-07-01 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictPlaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=20)),
                ('specific_place', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A Positive(A+)'), ('A-', 'A Negative(A-)'), ('B+', 'B Positive(B+)'), ('B-', 'B Negative(B-)'), ('AB+', 'AB Positive(AB+)'), ('AB-', 'AB Negative(AB-)'), ('O+', 'O Positive(O+)'), ('O-', 'O Negative(O-)')], max_length=5),
        ),
        migrations.CreateModel(
            name='BloodDonationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
