# Generated by Django 2.2.7 on 2020-07-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_auto_20200701_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donordetails',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A Positive(A+)'), ('A-', 'A Negative(A-)'), ('B+', 'B Positive(B+)'), ('B-', 'B Negative(B-)'), ('AB+', 'AB Positive(AB+)'), ('AB-', 'AB Negative(AB-)'), ('O+', 'O Positive(O+)'), ('O-', 'O Negative(O-)')], max_length=5),
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='district',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='is_available',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='last_date_of_donation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='present_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='specific_area',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
