# Generated by Django 2.2.7 on 2020-07-12 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_auto_20200711_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donordetails',
            name='id',
        ),
        migrations.AddField(
            model_name='blooddonationhistory',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donordetails',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donordetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
