# Generated by Django 2.2.7 on 2020-07-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_auto_20200712_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_details', to='donors.DonorDetails'),
        ),
    ]
