# Generated by Django 2.2.7 on 2020-07-17 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_auto_20200718_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonationhistory',
            name='donor_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donor_details', to='donors.DonorDetails'),
        ),
        migrations.AlterField(
            model_name='blooddonationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
