# Generated by Django 2.2.7 on 2020-07-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_auto_20200718_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonationhistory',
            name='donor_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_details', to='donors.DonorDetails'),
        ),
    ]
