# Generated by Django 2.2.7 on 2020-07-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytotaldonate',
            name='total_abn_donate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaldonate',
            name='total_abp_donate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaldonate',
            name='total_an_donate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaldonate',
            name='total_ap_donate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaldonate',
            name='total_bn_donate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaldonate',
            name='total_bp_donate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaldonate',
            name='total_donate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaldonate',
            name='total_on_donate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaldonate',
            name='total_op_donate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaljoin',
            name='total_abn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaljoin',
            name='total_abp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaljoin',
            name='total_an',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaljoin',
            name='total_ap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaljoin',
            name='total_bn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaljoin',
            name='total_bp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaljoin',
            name='total_on',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaljoin',
            name='total_op',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlytotaljoin',
            name='total_user',
            field=models.IntegerField(default=0),
        ),
    ]
